name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build Release
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-pc-windows-msvc

      - name: Build
        run: cargo build --release --verbose

      - name: Prepare Artifacts and Zip
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path release_artifacts
          Copy-Item -Path "target/release/injector.exe" -Destination "release_artifacts/"
          Copy-Item -Path "target/release/overlay.dll" -Destination "release_artifacts/"
          Set-Location release_artifacts
          7z a ../YAT.zip *

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: YAT.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
